//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DersTablo()
        {
            this.OgrenciDersTabloes = new HashSet<OgrenciDersTablo>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public double Kredisi { get; set; }
        public int OkulYonetimId { get; set; }
    
        public virtual OkulYonetimTablo OkulYonetimTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDersTablo> OgrenciDersTabloes { get; set; }
    }
}
