//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselProgramlama
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdareDBEntities : DbContext
    {
        public IdareDBEntities()
            : base("name=IdareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DersTablo> DersTabloes { get; set; }
        public virtual DbSet<OgrenciDersTablo> OgrenciDersTabloes { get; set; }
        public virtual DbSet<OgrenciTablo> OgrenciTabloes { get; set; }
        public virtual DbSet<OkulYonetimTablo> OkulYonetimTabloes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
