//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GörselProgramlama
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciDersTablo
    {
        public int Id { get; set; }
        public int DersId { get; set; }
        public int OgrenciId { get; set; }
    
        public virtual DersTablo DersTablo { get; set; }
        public virtual OgrenciTablo OgrenciTablo { get; set; }
    }
}
